import { routing } from "@/i18n/routing";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { Cairo, Poppins } from "next/font/google";
import '../globals.css'
import 'swiper/css';
import AuthProvider from "@/providers/AuthProvider";
import AppProvider from "@/providers/AppProvider";
import HeaderUser from "@/layouts/HeaderUser";


const CairoFont = Cairo({
  subsets: ["latin"],
  variable: "--font-cairo",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
})
const PoppinsFont = Poppins({
  subsets: ["latin"],
  variable: "--font-cairo",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale || 'en'} dir={locale === 'ar' ? 'rtl' : 'ltr'} data-theme=''>
      <body
        className={`${locale === 'ar' ? CairoFont.className : PoppinsFont.className} antialiased`}
      >
        <NextIntlClientProvider>
          <AuthProvider>
            <AppProvider>
              <HeaderUser />
              {children}
            </AppProvider>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}